import Head from "next/head";
import { getAllCollections } from "../helpers/api-utils";

import CollectionMasonry from "../components/collections/collection-masonry";

const Home = (props) => {
  return (
    <div>
      <Head>
        <title>Pak Jiwoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {props.collection && <CollectionMasonry collection={props.collection} />}
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  const allCollections = await getAllCollections();

  return {
    props: { collection: allCollections },
    revalidate: 60,
  };
};
