import Head from "next/head";
import { useState } from "react";
import { getAllCollections } from "../helpers/api-utils";
import styles from "../styles/Home.module.scss";

const Home = (props) => {
  const [collections, setCollections] = useState(props.collections);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Collage
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const collections = await getAllCollections();

  return {
    props: { collections: collections },
  };
};

export default Home;
